from turtle import *
speed(300)
def back():
    penup()
    goto (-200,-200)
    pendown()
    begin_fill()
    color("green")
    for i in range(2):
        forward (400)
        left(90)
        forward(200)
        left(90)

    end_fill()
    exitonclick()
back()
def sky():
    penup()
    goto(-200,+200)
    pendown()
    begin_fill()
    color("dark blue")
    forward(400)
    right(90)
    forward(200)
    right(90)
    forward(400)
    right(90)
    forward(200)
    end_fill()

sky()


def house():
    penup()
    goto (-180, -100)
    right(90)
    color("grey")
    pendown()
    begin_fill()
    forward(100)
    left(90)
    forward(150)
    left(90)
    forward(100)
    left(90)
    forward(150)
    end_fill()
house() 

def window():
    begin_fill()
    color("yellow")
    for g in range(4):
        forward(20)
        left(90)
    end_fill()
penup()
goto (-170,40)
window()
goto (-140,40)
window()
goto (-110,40)
window()
goto (-170,10)
window()
goto (-140,10)
window()
goto (-110,10)
window()
goto (-170,-20)
window()
goto (-140,-20)
window()
goto (-110,-20)
window()
goto (-170,-50)
window()
goto (-140,-50)
window()
goto (-110,-50)
window()
pendown()

def door():
    color("brown")
    begin_fill()
    for u in range(4):
        forward (15)
        left(90)
    end_fill()
penup()
goto (-140,-85)
pendown()
door()
def moon():
    penup()
    goto(140,150)
    pendown()
    color("yellow")
    begin_fill()
    circle(20)
    end_fill()
moon()
def forest(x,y,a,b):
    color ("brown")
    penup()
    goto(x,y)
    pendown()
    begin_fill()
    left(90)
    forward(10)
    left(90)
    forward(10)
    left(90)
    forward(10)
    left(90)
    forward(10)
    end_fill()
    left(90+90)
    forward(10)
    begin_fill()
    color("dark green")
    right(90)
    forward(15)
    for g in range(3):
        left(130)
        forward(15)
        right(130)
        forward(10)
    goto(a,b)
    for j in range(4):
        right(130)
        forward(15)
        left(130)
        forward(10)
    end_fill()
forest(-50,-100,-45,-44)
#forest(-50,-100,-45,-44)
hideturtle()

    